# Where things are
source:       .
destination:  ./_site
plugins_dir:      ./_plugins
layouts_dir:      ./_layouts
gems: [jekyll-paginate]
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4008
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: thinking
description: java,c#,html
keywords: java,c#,html
url: http://www.gisthinking.com
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: miaojing
    email: miaojinggis@outlook.com
    imageLink: /images/header.jpg
    simpleIntro: 晨鸡初报，昏鸦早噪，哪一个不在红尘里闹。路遥遥，水迢迢，利名人上长安道。今日少年明日老，山依旧，人不见了,可笑可笑..
    detailIntro:
      <p>GIS界的程序猿</p>
      <p>主要使用Java,c#,html</p>
      <p>不断学习中...</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-github-alt
    url: https://github.com/miaojingThink

#Links
customLinks:
  - item:
    - text: 技术小黑屋
      url: http://droidyue.com/
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.gisthinking.com/themes.html
    message: Friends    
  - item:
    - text: Java Code Geeks
      url: http://www.javacodegeeks.com/
    - text: Web Developer
      url: http://www.fromdev.com/
    - text: BeginnersBook
      url: http://beginnersbook.com/
    - text: Mkyong
      url: http://www.mkyong.com/
    - text: Java By Nataraj
      url: http://javabynataraj.blogspot.in/
    message: About Java

#baidu share config
baiduShare:
  config: true